name: CI - Kalkulator Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-kalkulator:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Jalankan Program kalkulator.py
      run: |
        python kalkulator.py
