name: Build & Run C++ Kalkulator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install g++
      run: sudo apt update && sudo apt install -y g++

    - name: Compile C++ Program
      run: |
        g++ -Wall -Wextra -Werror kalkulator.cpp -o kalkulator

    - name: Run Program (optional with timeout)
      run: |
        timeout 10s ./kalkulator || echo "Program exited or was terminated after timeout"
